// Load the API for handling errors
var createError = require('http-errors');
// Load the express API for REST services (Routers)
var express = require('express');
// Load the path API
var path = require('path');
// Load the cookie parser API
var cookieParser = require('cookie-parser');
// Load the body parser API
var bodyParser = require('body-parser');
// Load the API for logging
var logger = require('morgan');
var compress = require('compression');

const passport = require('passport');

// Configure Mongoose
const configureMongoose = require('./config/mongoose');

const db = configureMongoose();

require('./controllers/auth.controller');

// Load the REST service for the index EJS template
var indexRouter = require('./routes/index');
// Load the REST service for users (generated by express generator)
var usersRouter = require('./routes/users');
// Load the contact router (for contact template page)
var contactRouter = require('./routes/contact');
// Load the login router
const loginRouter = require('./routes/login');
// Load the business contact route to be secured
const secureRouter = require('./routes/business-contacts');

// Instantiate the express application
var app = express();

// view engine setup: set it to ejs engine
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');


if (process.env.NODE_ENV === 'development') {
  app.use(logger('dev'));
} else if (process.env.NODE_ENV === 'production') {
  app.use(compress());
}

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(bodyParser());
app.use(express.static(path.join(__dirname, 'public')));

//Instruct express app to bind the REST services to the corresponding URIs
app.use('/', indexRouter);
app.use('/users', usersRouter);
// Add the contact Router to the express app (for contact template page)
app.use('/contact', contactRouter);
// Add the login Router to the express app
app.use('/login', loginRouter);
// Add a secure router to the express app (only logged users can access this router)
app.use('/my-contacts', passport.authenticate('jwt', { session: false , failureRedirect: '/login?redirectUrl=/my-contacts'}), secureRouter);
// { successRedirect: '/',
//                                    failureRedirect: '/login' }

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

// Export the express application
module.exports = app;

