// Load the API for handling errors
var createError = require('http-errors');
// Load the express API for REST services (Routers)
var express = require('express');
// Load the path API
var path = require('path');
// Load the cookie parser API
var cookieParser = require('cookie-parser');
// Load the API for logging
var logger = require('morgan');
var compress = require('compression');

// Configure Mongoose
process.env.NODE_ENV = process.env.NODE_ENV || 'development';
const configureMongoose = require('./config/mongoose');

const db = configureMongoose();

// Configure Passport
const passport = require('./config/passport');
var passport = passport();

// Load the REST service for the index EJS template
var indexRouter = require('./routes/index');
// Load the REST service for users (generated by express generator)
var usersRouter = require('./routes/users');
// Import the contact router (for contact template page)
var contactRouter = require('./routes/contact');
// Instantiate the express application
var app = express();

// view engine setup: set it to ejs engine
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// Configure express with logging, json, urlencoded, cookie parser, and static path for resources
if (process.env.NODE_ENV === 'development') {
  app.use(logger('dev'));
} else if (process.env.NODE_ENV === 'production') {
  app.use(compress());
}

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

//Instruct express app to bind the REST services to the corresponding URIs
app.use('/', indexRouter);
app.use('/users', usersRouter);
// Add the contact Route to the express app (for contact template page)
app.use('/contact', contactRouter);
// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

// Export the express application
module.exports = app;

